config/routes.rb
Uniqueness::Application.routes.draw do
  resources :lists, except: :show do
    resources :items do
      collection do
        post :sort
      end
    end
  end
  root to: "lists#index"
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, -> { order :position }, class_name: "ListItem"
  validates_presence_of :name
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :list
  validates_presence_of :name, :list, :position

  before_validation :ensure_position

  def self.update_positions(ids)
    transaction do
      connection.execute "set constraints list_item_position deferred"
      ids.each_with_index do |id, index|
        where(id: id).update_all(position: index + 1)
      end
    end
  end

  private
  def ensure_position
    self.position ||= self.class.where(list_id: list_id).maximum(:position).to_i + 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  expose(:list)
  expose(:items) { list.items }
  expose(:item, attributes: :item_params, model: ListItem, ancestor: :items)

  respond_to :json

  def create
    item.save
    respond_with item, location: lists_path
  end

  def sort
    items.update_positions(params[:list_item_ids])
    head :ok
  end

  private

  def item_params
    params.require(:list_item).permit(:name)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  expose(:lists) { List.includes(:items) }
  expose(:list, attributes: :list_params)

  def index
  end

  def create
    list.save
    redirect_to lists_path
  end
  alias update create

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uniqueness</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"  %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/list_items/_list_item.html.erb
<li data-id="<%= list_item.id %>"><%= list_item.name %></li>

app/views/lists/_form.html.erb
<%= form_for list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit list</li>
<%= render 'form' %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<ul class="lists">
<% lists.each do |list| %>
  <li class="list">
    <h2>
      <%= list.name %>
      (<%= link_to "edit", edit_list_path(list) %>)
    </h2>

    <ul class="items" data-sort-url="<%= sort_list_items_path(list) %>">
      <%= render list.items %>
    </ul>

    <%= form_for list.items.build, url: list_items_path(list), remote: true do |list_form| %>
      <%= list_form.text_field :name, placeholder: "Add an item" %><button type="submit">+</button>
    <% end %>
  </li>
<% end %>
</ul>

<p><%= link_to "New list", new_list_path %></p>

app/views/lists/new.html.erb
<h1>New list</li>
<%= render 'form' %>